# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('deporte', 'deporte'), ('carrera', 'carrera'), ('terror', 'terror'), ('disparo', 'disparo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='console',
            field=models.CharField(choices=[('Ps3', 'Ps3'), ('Ps4', 'Ps4')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_game',
            field=models.CharField(choices=[('Full Game', 'Full Game'), ('Season Pass', 'Season Pass'), ('DLC', 'DLC')], max_length=100),
        ),
    ]
