# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170901_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('disparo', 'disparo'), ('deporte', 'deporte'), ('terror', 'terror'), ('carrera', 'carrera')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
