# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170901_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('deporte', 'deporte'), ('terror', 'terror'), ('disparo', 'disparo'), ('carrera', 'carrera')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_game',
            field=models.CharField(choices=[('DLC', 'DLC'), ('Season Pass', 'Season Pass'), ('Full Game', 'Full Game')], max_length=100),
        ),
    ]
