# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170907_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('ps3', 'ps3'), ('ps4', 'ps4')], default='ps3', max_length=255),
        ),
    ]
