# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170909_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='typeofgame',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='TypeOfGame',
        ),
    ]
